services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:?error}
      POSTGRES_USER: ${DB_USER:?error}
      POSTGRES_DB: cinema_data
    ports:
      - 8081:5432
    networks:
      - cinema_data_network

networks:
  cinema_data_network:
    driver: bridge